name: Release

on:
  push:
    branches:
      - main

jobs:
  No-release:
    if: ${{ github.ref != 'refs/heads/main' }}
    runs-on: ubuntu-latest
    timeout-minutes: 17
    steps:
      - name: No release
        run: echo "Branch is not main, no need to release."

  execute-semantic-release:
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/semantic-release.yml
    with:
      branches: "main"
    secrets:
      token: ${{ secrets.SHARED_WORKFLOW_TOKEN }}
