name: Node.js Test

on:
  workflow_call:
    inputs:
      # <--------------- ESLint Setting ---------------> 
      eslint-enable:
        required: false
        type: boolean
        description: Enable ESLint
        default: false

      eslint-command:
        required: false
        type: string
        description: ESLint command
        default:  npx eslint --config eslint.config.mjs '**/*.{js,ts,tsx}' || exit 1

      # <--------------- UNIT-TEST SETTINGS --------------> 
      unit-test-enable:
        required: false
        type: boolean
        description: "To disable the unit-tests job set to false"
        default: true
      unit-test-command:
        required: false
        type: string
        description: "Used to override the default command to run your unit tests e.g. yarn test:unit-ci"
        default: "npm run test:unit-ci"

      node-version:
        required: false
        type: string
        description: Node.js version
        default: '21'  # Default version of Node.js

    secrets:
      token:
        required: true 

jobs:
  # <---------------------- ESLINT ----------------------> 
  eslint:
    name: ESLint Check
    runs-on: ubuntu-22.04
    if: ${{ inputs.eslint-enable }}
    steps:
      # Check out the calling repository
      - name: Checkout Source
        uses: actions/checkout@v4
      
      # Checkout the workflows repo to access `eslint.config.mjs`
      - name: Checkout Workflows Repo
        uses: actions/checkout@v4
        with:
          # Checkout the `eslint` branch
          repository: Ridvan-bot/workflows
          ref: dev
          path: workflows-repo
          fetch-depth: 1

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      - name: Install Dependencies
      # Install dependencies and copy the eslint config file
        run: |
          # Install dependencies
          npm install
          npm install eslint typescript-eslint eslint-plugin-react globals @eslint/js --save-dev
          cp workflows-repo/eslint.config.mjs ./

      - name: Run ESLint
        run: |
            export CI=true
            ${ inputs.eslint-command }
        
        