name: Prep Google Cloud With Required Infrastructure

# Trigger this workflow manually with inputs for branch and project name
on:
  workflow_call:
    inputs:
      project_name:
        description: 'Google Cloud Project name (e.g., dev-my-project or main-my-project)'
        required: true
        type: string
      customer_name:
        description: 'Customer name'
        required: true
        type: string
      branch:
        description: 'Select branch (e.g., dev or main)'
        required: true
        type: string
    secrets:
      token:
        required: true
      credentials_json:
        required: true

jobs:
  setup-project:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Branch Name
        id: branch_name
        run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.credentials_json }}
          access_token_scopes: https://www.googleapis.com/auth/cloud-platform

      - name: Configure gcloud CLI
        run: |
          gcloud config set project ${{ github.event.inputs.project_name }}
          gcloud config set run/region europe-west1

      - name: Enable Google APIs
        run: |
          gcloud services enable containerregistry.googleapis.com
          gcloud services enable cloudbuild.googleapis.com
          gcloud services enable artifactregistry.googleapis.com
          gcloud services enable run.googleapis.com
