name: Semantic Release

on:
  workflow_call:
    inputs:
      branches:
        required: true
        type: string
      releaserc_path:
        required: false
        type: string
      slack_enabled:
        required: false
        type: boolean
        default: false
      npm_publish_enabled:
          required: false
          type: boolean
          default: false
      teams_enabled:
        required: false
        type: boolean
        default: false
    secrets:
      token:
        required: true
      slack_webhook:
        required: false
      npm_token:
        required: false
jobs:
  Execute-Semantic-release:
    if: ${{ inputs.branches == 'main' }}
    runs-on: ubuntu-22.04
    timeout-minutes: 17

    steps:
      # Check out the calling repository
      - name: Checkout calling repository
        uses: actions/checkout@v4

      # Check out the `workflow` repo for the default config if needed
      - name: Checkout workflow repo for default config
        if: ${{ !inputs.releaserc_path }}
        uses: actions/checkout@v4
        with:
          repository: Ridvan-bot/workflows
          path: workflow

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install dependencies in the correct directory
      - name: Install dependencies
        run: |
          # Install dependencies
          npm install

      # Use the input .releaserc.json if provided, otherwise use the default one from the `workflow` repo
      - name: Copy .releaserc.json
        run: |
          if [ -f "${{ inputs.releaserc_path }}" ]; then
            cp "${{ inputs.releaserc_path }}" ./.releaserc.json
          else
            cp "${{ github.workspace }}/workflow/.releaserc.json" ./.releaserc.json
          fi

      # Run Semantic Release
      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release
  
  Notify-slack:
    if: ${{ needs.execute-semantic-release.result == 'success' && inputs.slack_enabled }}
    needs: Execute-Semantic-release
    runs-on: ubuntu-latest
    timeout-minutes: 17
    steps:
      - uses: actions/checkout@v4
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

  Push-npm-package-to-npm-registry:
      if: ${{ needs.execute-semantic-release.result == 'success' && inputs.npm_publish_enabled }}
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '18'
        - name: Install dependencies
          run: npm install
        - name: Publish to npm
          run: npm publish
          env:
            NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

