name: Semantic Release

on:
  workflow_call:
    inputs:
      branches:
        required: true
        type: string
      releaserc_path:
        required: false
        type: string
        default: './workflow/.releaserc.json'
      repo_path:
        required: false
        type: string
        default: './pohlmanprotean.se/'

jobs:
  Execute-Semantic-release:
    if: ${{ inputs.branches == 'dev' }}
    runs-on: ubuntu-22.04

    steps:
      # Check out the calling repository
      - name: Checkout calling repository
        uses: actions/checkout@v4
        with:
          path: ${{ github.workspace }}  # Use the default workspace path

      # Check out the `workflow` repo for the default config if needed
      - name: Checkout workflow repo for default config
        if: ${{ !inputs.releaserc_path }}
        uses: actions/checkout@v4
        with:
          repository: Ridvan-bot/workflows
          path: workflow

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install dependencies in the correct directory
      - name: Install dependencies
        run: |
          # Show the current working directory before changing
          echo "Current working directory before navigation:"
          pwd
          # Navigate up one level to `/home/runner/work/website/` and then to `repo_path`
          echo "Changing directory to: ${{ inputs.repo_path }}"
          cd ${{ github.workspace }}/..${{ inputs.repo_path }}  # Navigate to the correct repo path
          # Show the new working directory after changing
          echo "New working directory after navigation:"
          pwd
          # Install dependencies
          npm install

      # Use the input .releaserc.json if provided, otherwise use the default one from the `workflow` repo
      - name: Copy .releaserc.json
        run: |
          if [ -f "${{ inputs.releaserc_path }}" ]; then
            cp "${{ inputs.releaserc_path }}" ./.releaserc.json
          else
            cp ./workflow/.releaserc.json ./.releaserc.json
          fi

      # Run Semantic Release
      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ${{ github.workspace }}/..${{ inputs.repo_path }}  # Navigate to the correct repo path
          npx semantic-release
