name: Semantic Release

on:
    workflow_call:
        inputs:
            branches:
                required: true
                type: string
jobs:
  Execute-Semantic-release:
    if: ${{ inputs.branches == 'main' }}
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Release
        run: echo "I'm Releasing"
