name: Semantic Release

on:
    workflow_call:
        inputs:
            branches:
                required: true
                type: string

        secrets:
            GITHUB_TOKEN: {
                required: true
            }
jobs:
  echo_message:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Echo "I'm working"
        run: echo "I'm working"
